//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetPlatejei
{
    using System;
    using System.Collections.Generic;
    
    public partial class analiz
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int user_id { get; set; }
        public Nullable<int> create { get; set; }
        public Nullable<int> delete { get; set; }
        public Nullable<int> update { get; set; }
    
        public virtual user user { get; set; }
    }
}
